# Generated by Django 5.1.3 on 2025-01-14 14:26

import chat.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_based', models.BooleanField(default=False)),
                ('duration', models.PositiveIntegerField(default=1, help_text='Duration in hours if time-based')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('total_customers', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('avg_stay_time', models.DurationField(default=datetime.timedelta(0))),
                ('todays_special', models.TextField()),
                ('total_messages', models.IntegerField(default=0)),
                ('var_id', models.CharField(blank=True, default=chat.models.generate_unique_var_id, max_length=6, null=True, unique=True)),
                ('qr_gen_frequency', models.CharField(choices=[('hourly', 1), ('daily', 24), ('weekly', 168), ('monthly', 730)], max_length=20)),
                ('var_id_gen_time', models.DateTimeField(auto_now=True)),
                ('var_id_expiry_time', models.DateTimeField(editable=False)),
                ('total_qr_scanned', models.IntegerField(default=0)),
                ('token_refresh_frequency', models.PositiveIntegerField(default=1, help_text='Time in hours')),
                ('customers', models.ManyToManyField(blank=True, related_name='visited_restaurants', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.restaurant')),
            ],
        ),
    ]
