# Generated by Django 5.1.3 on 2025-01-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='var_id_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
