# Generated by Django 5.1.3 on 2024-12-26 07:04

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_variable_id_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='variable_id_expiry',
            field=models.DateTimeField(default=chat.models.default_variable_id_expiry, editable=False),
        ),
    ]
