# Generated by Django 5.1.3 on 2024-12-26 07:15

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_variable_id_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_expiry',
            field=models.DateTimeField(default=chat.models.default_variable_id_expiry, editable=False),
        ),
    ]
