# Generated by Django 5.1.3 on 2025-01-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('platform_owner', 'Platform Owner'), ('restaurant_owner', 'Restaurant Owner'), ('customer', 'Customer')], max_length=20),
        ),
    ]
